[fish] Switching fish theme to startship

diff --git a/bin/Matching b/bin/Matching
--- a/bin/Matching
+++ b/bin/Matching
@@ -1,1 +1,15 @@
-./clearssh.sh
+#!/bin/sh
+
+eval "value=\$$#"
+
+if [ "$#" -lt 1 ] ; then
+  echo "Invalid arguments."
+  exit 1
+fi
+
+if ! echo "$value" | egrep -q '.*:[0-9]+$' ; then
+  echo "Invalid file:lineno format: $value"
+  exit 1
+fi
+
+echo "$value" | awk -F: '{print "sed -i -e "$2"d",$1}' | sh -x
